dist: trusty
language: cpp
services: docker

os: linux

cache:
  directories:
    - $HOME/.ccache

stages:
  - test # Default stage with job matrix

compiler:
  - gcc

env:
  global:
    - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
  matrix:
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="xenial" GAZEBO_VERSION=gazebo7 BUILD_TESTING=OFF
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="xenial" GAZEBO_VERSION=gazebo8 BUILD_TESTING=ON
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="bionic" GAZEBO_VERSION=gazebo9 BUILD_TESTING=ON
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="bionic" GAZEBO_VERSION=gazebo10 BUILD_TESTING=ON
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="bionic" GAZEBO_VERSION=gazebo11 BUILD_TESTING=ON
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="focal" GAZEBO_VERSION=gazebo9 BUILD_TESTING=ON
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="focal" GAZEBO_VERSION=gazebo10 BUILD_TESTING=ON
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="focal" GAZEBO_VERSION=gazebo11 BUILD_TESTING=ON

# ===================
# STAGE: test (linux)
# ===================

before_script:
  - docker pull ubuntu:$UBUNTU

script:
  - >-
    docker run -it \
      -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
      -v $HOME/.ccache:$HOME/.ccache \
      -w $TRAVIS_BUILD_DIR \
      --env CC \
      --env CXX \
      --env TRAVIS_BUILD_DIR \
      --env TRAVIS_BUILD_TYPE \
      --env TRAVIS_CMAKE_GENERATOR \
      --env GAZEBO_VERSION \
      --env BUILD_TESTING \
      ubuntu:$UBUNTU \
      sh .ci/install_debian_and_script.sh

notifications:
  email:
    - pegua1@gmail.com
